trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "TFE_Run"
    displayName: "Terraform Enterprise Run"
    jobs:
      - job: "TFE_Run_Job"
        displayName: "Terraform Enterprise Run"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          # - task: Bash@3
          #   displayName: "Archive Terraform Code"
          #   inputs:
          #     filePath: "pipeline/archiveTerraform.sh"
          - task: UsePythonVersion@0
            displayName: "Select Python3"
            inputs:
              versionSpec: "3.7"
          - script: python -m pip install --upgrade pip requests
            displayName: "Install Python3 tools"
          - task: PythonScript@0
            displayName: "Archive Terraform Code"
            inputs:
              scriptSource: "filePath"
              scriptPath: "pipeline/archiveTerraform.py"
          - task: PythonScript@0
            displayName: "Get Workspace Id from TFE"
            inputs:
              scriptSource: "filePath"
              scriptPath: "pipeline/getWorkspaceId.py"
              arguments: "-tfeToken $(tfeToken)"
          - task: PythonScript@0
            displayName: "Create Configuration Version"
            inputs:
              scriptSource: "filePath"
              scriptPath: "pipeline/createConfigurationVersion.py"
              arguments: "-tfeToken $(tfeToken)"
          - task: PythonScript@0
            displayName: "Create Run"
            inputs:
              scriptSource: "filePath"
              scriptPath: "pipeline/createRun.py"
              arguments: "-tfeToken $(tfeToken)"
          - task: PythonScript@0
            displayName: "Monitor Run"
            inputs:
              scriptSource: "filePath"
              scriptPath: "pipeline/monitorRun.py"
              arguments: "-tfeToken $(tfeToken)"
